version: "3.3"

networks:
  socket_proxy:
    name: socket_proxy
    ipam:
      config:
        - subnet: ${SOCKET_PROXY_SUBNET} #change subnet as necessary

services:
  socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy
    environment:
      - LOG_LEVEL=info
      - EVENTS=1
      - PING=1
      - VERSION=1
      - CONTAINERS=1
      - IMAGES=1
      - NETWORKS=1
      - VOLUMES=1
      - POST=1
      - SERVICES=1
      - INFO=1
      - TASKS=1
      - AUTH=0
      - SECRETS=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - DISTRIBUTION=0
      - EXEC=0
      - GRPC=0
      - NODES=0
      - PLUGINS=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0

    ports:
      - ${SOCKET_PROXY_PORT}:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: always
    networks:
      socket_proxy:
        ipv4_address: ${SOCKET_PROXY_IP_ADDRESS}