services:
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/appdata/grocy:/config
    ports:
      - 2000:80
    restart: unless-stopped
