version: "3"

networks:
  socket_proxy:
    name: socket_proxy

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - DOCKER_HOST=tcp://${SOCKET_PROXY_IP_ADDRESS}:${SOCKET_PROXY_PORT}
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      - WATCHTOWER_HTTP_API_METRICS=TRUE
      - WATCHTOWER_POLL_INTERVAL=60
    networks:
      - socket_proxy
    ports:
      - 8080:8080
    deploy:
      labels:
        com.centurylinklabs.watchtower.depends-on: socket-proxy
    restart: always