version: '3'

networks:
  socket_proxy:
    name: socket_proxy

services: 
  portainer: 
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - portainer_data:/data
    ports:
      - ${PORTAINER_PORT}:9000
    command: -H tcp://socket-proxy:${SOCKET_PROXY_PORT}
    environment:
      - DOCKER_HOST=tcp://${SOCKET_PROXY_IP_ADDRESS}:${SOCKET_PROXY_PORT}
    networks:
      - socket_proxy

volumes:
  portainer_data:
